name: Run JUnit Tests with Selenium

on:
  push:
    branches:
      - main  # Trigger when there is a push to the main branch
  pull_request:
    branches:
      - main  # Trigger when a pull request is made to the main branch

jobs:
  test:
    runs-on: windows-latest  # This uses the latest Windows environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '22'  # Specify the Java version
          distribution: 'zulu'  # Use OpenJDK
          architecture: 'x64'

      - name: Clear Chocolatey Cache
        run: Remove-Item -Recurse -Force "$env:TEMP\chocolatey" -ErrorAction Ignore
        shell: pwsh

      - name: Install Google Chrome
        run: |
          choco install googlechrome -y --ignore-checksums
        shell: pwsh

      - name: Install ChromeDriver
        run: |
          choco install chromedriver -y --ignore-checksums
        shell: pwsh

      - name: Set ChromeDriver path as environment variable
        run: |
          echo "CHROMEDRIVER_PATH=$(Get-Command chromedriver | Select-Object -ExpandProperty Definition)" >> $GITHUB_ENV
        shell: pwsh
        # This ensures the correct path to ChromeDriver is set dynamically

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: C:\Users\Vova\.m2\repository  # Windows-specific Maven cache path
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install  # Build your project and download dependencies

      - name: Run Mouse Tests
        run: mvn test -Dgroups=mouse_tests
