name: Run JUnit Tests with Selenium

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to latest version

      - name: Set up Java
        uses: actions/setup-java@v3  # Updated to latest version
        with:
          java-version: '22'
          distribution: 'zulu'
          architecture: 'x64'

      - name: Install Google Chrome & ChromeDriver
        run: |
          choco install googlechrome -y --ignore-checksums
          choco install chromedriver -y --ignore-checksums
        shell: pwsh

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test

      - name: Install Allure CLI
        run: |
          curl -o allure.zip -Ls "https://github.com/allure-framework/allure2/releases/latest/download/allure-commandline.zip"
          powershell -Command "Expand-Archive -Path allure.zip -DestinationPath allure"
          echo "${{ github.workspace }}/allure/bin" >> $GITHUB_PATH

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: allure-report
          path: target/site/allure-maven