name: Run JUnit Tests with Selenium

on:
  push:
    branches:
      - main  # Trigger when there is a push to the main branch
  pull_request:
    branches:
      - main  # Trigger when a pull request is made to the main branch

jobs:
  test:
    runs-on: windows-latest  # This uses the latest Windows environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '22'  # Specify the Java version
          distribution: 'zulu'  # Use OpenJDK
          architecture: 'x64'

      - name: Set up ChromeDriver
        uses: actions/setup-chrome@v2
        with:
          chromedriver-version: '132.0.6834.159'  # Specify the version of ChromeDriver you're using

      - name: Install Google Chrome
        run: |
          choco install googlechrome --version 132.0.6834.159  # Install the specific version of Google Chrome for Windows

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: C:\Users\Vova\.m2\repository  # Windows-specific Maven cache path
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install  # Build your project and download dependencies

      - name: Run tests with Maven
        run: mvn test  # Run JUnit tests with Maven
